### ISSUE TITLE
mistral-7B模型权重

### ISSUE THREAD

**Issue by LookingYu** [THUDM/AutoRE#13]
您好，HuggingFace的链接模型权重是vicuna-7b-v1.5的，请问能麻烦您提供一下Mistral-7B-Instruct-v0.2的模型权重吗？非常感谢

**Comment by bigdante** [comment]
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2，貌似有？

**Comment by LookingYu** [comment]
> [https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2，貌似有？](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2%EF%BC%8C%E8%B2%8C%E4%BC%BC%E6%9C%89%EF%BC%9F)

哦哦，我的，我本来想问的是有没有就是Mistral-7B对应的lora模块，因为我看您分享的是vicuna-7b对应的好像是，，不过我最近把代码跑起来了，也不好意思再麻烦您了，，非常感谢您的回复！
