### ISSUE TITLE
A question about pre_process_data.py

### ISSUE THREAD

**Issue by yanyi74** [THUDM/AutoRE#4]
<img width="1017" alt="截屏2024-05-23 17 27 30" src="https://github.com/bigdante/AutoRE/assets/116535337/94122afc-c00d-4ea4-b24b-167a6de4eeae">
pre_process_data.py file, D_R_H_F paradigm in that line of code should be fixed header entity, the code is not reflected, can you answer it, thank you!

**Comment by bigdante** [comment]
I'm sorry, when I was refactoring the code, I may have directly copied this line from another paradigm. You are right, it is necessary to ensure that fact[0] == subject. I apologize for my carelessness, and I have now updated the code.

Best～

**Comment by bigdante** [comment]
> <img alt="截屏2024-05-23 17 27 30" width="1017" src="https://private-user-images.githubusercontent.com/116535337/333127813-94122afc-c00d-4ea4-b24b-167a6de4eeae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODE2OTMsIm5iZiI6MTcxNjQ4MTM5MywicGF0aCI6Ii8xMTY1MzUzMzcvMzMzMTI3ODEzLTk0MTIyYWZjLWMwMGQtNGVhNC1iMjRiLTE2N2E2ZGU0ZWVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxNjIzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWFkMGU3Yzk2OTQ4ZjQ4ZDc5MzMwMjQ3MjZkNjkyMmY2YWI2MjYwZDQ1YzdjNTFiOGRmZTU5OWEzMGJiZDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.49_Fsr4h1_ktnljuPVbbizu6XV0nr56bjh4psjMRZYo"> pre_process_data.py file, D_R_H_F paradigm in that line of code should be fixed header entity, the code is not reflected, can you answer it, thank you!

I'm sorry, when I was refactoring the code, I may have directly copied this line from another paradigm. You are right, it is necessary to ensure that fact[0] == subject. I apologize for my carelessness, and I have now updated the code.

Best～

**Comment by yanyi74** [comment]
Thank you for your answer, I also have a question in mistral_lora_D_R_H_F_desc.sh where the path of this dataset corresponds to, I guess it is data/train/D_R_H_F/train.json, but the path in the script is not consistent, is it convenient to answer, thank you!
<img width="1010" alt="截屏2024-05-24 11 24 35" src="https://github.com/bigdante/AutoRE/assets/116535337/d4fc4af0-a6d8-4ff4-8b24-3f50113f6b93">
<img width="447" alt="截屏2024-05-24 11 22 18" src="https://github.com/bigdante/AutoRE/assets/116535337/13fbb8a8-6b98-4be4-b2ef-7c20737bb007">

**Comment by bigdante** [comment]
> Thank you for your answer, I also have a question in mistral_lora_D_R_H_F_desc.sh where the path of this dataset corresponds to, I guess it is data/train/D_R_H_F/train.json, but the path in the script is not consistent, is it convenient to answer, thank you! <img alt="截屏2024-05-24 11 24 35" width="1010" src="https://private-user-images.githubusercontent.com/116535337/333434159-d4fc4af0-a6d8-4ff4-8b24-3f50113f6b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjE0NTEsIm5iZiI6MTcxNjUyMTE1MSwicGF0aCI6Ii8xMTY1MzUzMzcvMzMzNDM0MTU5LWQ0ZmM0YWYwLWE2ZDgtNGZmNC04YjI0LTNmNTAxMTNmNmI5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMzI1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjMzMzYwZWY1Mjk5ZDY0ZTAxNGQ0NTU3OTMzZWFmODRlMDg4ODgwZGY2ODA2MjUxMDkyNDJjYjEwM2VlZWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-PO9kqkD_V6GAcvADdW1dCflxXrOx6WtkCydglZhezc"> <img alt="截屏2024-05-24 11 22 18" width="447" src="https://private-user-images.githubusercontent.com/116535337/333433404-13fbb8a8-6b98-4be4-b2ef-7c20737bb007.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjE0NTEsIm5iZiI6MTcxNjUyMTE1MSwicGF0aCI6Ii8xMTY1MzUzMzcvMzMzNDMzNDA0LTEzZmJiOGE4LTZiOTgtNGJlNC1iMmVmLTdjMjA3MzdiYjAwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMzI1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGNhYTNkODMzOWMxN2U0YjNkNjNjYzFiNDkwMDcyODU1YzI4OWU4MTI3OTQzZjhkM2Y0M2ExMTE1OGQzNmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a1Tsg8viRLO3OD4oxVwPzpCFdWqsIMsDHTar0KqHGjc">

I use LLama-factory code, the actual paths are all in the dataset_info.json which is in the data folder.

Best~
